# Code to read images from FVC2006 DB2_A

In [2]:
import cv2
import os
# Get the path to the images
images_path = '/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/ICVGIP_reproduce/FVC2006DB2A'
# fvc2006db2a

In [3]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import numpy as np

2023-07-27 09:50:29.621640: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
import cv2
import numpy as np
def random_distortion(image):
    rows, cols = image.shape[:2]
    # Define the distortion parameters
    random_scale = np.random.uniform(0.8, 1.2)
    random_angle = np.random.uniform(-15, 15)
    random_translation = np.random.uniform(-10, 10, (2,))
    # Apply the distortion
    M = cv2.getRotationMatrix2D((cols/2, rows/2), random_angle, random_scale)
    M[:, 2] += random_translation
    distorted_image = cv2.warpAffine(image, M, (cols, rows))
    # print(distorted_image.shape)
    return distorted_image

def random_gaussian_blurring(image):
    # Generate random blurring parameters
    random_sigma = np.random.uniform(0, 2.0)
    # Apply Gaussian blur
    blurred_image = cv2.GaussianBlur(image, (0, 0), random_sigma)
    # print(blurred_image.shape)
    return blurred_image

def random_rotation(image):
    rows, cols = image.shape[:2]
    # Generate random rotation angle
    random_angle = np.random.uniform(-30, 30)
    # Apply rotation
    M = cv2.getRotationMatrix2D((cols/2, rows/2), random_angle, 1)
    rotated_image = cv2.warpAffine(image, M, (cols, rows))
    # print(rotated_image.shape)
    return rotated_image

def random_scaling(image):
    rows, cols = image.shape[:2]
    # Generate random scaling factor
    random_scale = np.random.uniform(0.8, 1.2)
    # Apply scaling
    scaled_image = cv2.resize(image, (int(cols*random_scale), int(rows*random_scale)))
    scaled_image = cv2.resize(scaled_image, (cols, rows))
    # print(scaled_image.shape)
    return scaled_image

def random_contrast(image):
    # Generate random contrast factor
    random_factor = np.random.uniform(0.5, 1.5)
    # Apply contrast adjustment
    adjusted_image = np.clip(image * random_factor, 0, 255).astype(np.uint8)
    # print(adjusted_image.shape)
    return adjusted_image

def random_noise(image):
    # Generate random noise parameters
    random_mean = 0
    random_std = np.random.uniform(0, 30)
    # Apply Gaussian noise
    noise = np.random.normal(random_mean, random_std, image.shape).astype(np.uint8)
    noisy_image = np.clip(image + noise, 0, 255).astype(np.uint8)
    # print(noisy_image.shape)
    return noisy_image

def random_morphology(image):
    # Generate random kernel size for morphology operations
    kernel_size = np.random.randint(2, 7)
    # Generate random morphology operation
    morph_op = np.random.choice([cv2.MORPH_OPEN, cv2.MORPH_CLOSE])
    # Create the kernel
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (kernel_size, kernel_size))
    # Apply morphology operation
    morph_image = cv2.morphologyEx(image, morph_op, kernel)
    # print(morph_image.shape)
    return morph_image



In [5]:
# processed_images_path = '/home/rs/21CS91R01/research/2023_ICVGIP-Code/datasets/processed_images_path'
# if not os.path.exists(processed_images_path):
#     os.mkdir(processed_images_path)

# List to store preprocessed images
preprocessed_images_train = []
labels_train = []

preprocessed_images_test = []
labels_test = []

# Iterate over the images
for image_name in os.listdir(images_path):
    if image_name.endswith('.bmp'):
        # Extract the label from the image name without considering variations
        image_name_ex = image_name.split('.')[0]
        print(image_name_ex)
        image_no = image_name_ex.split('_')[0]
        print(image_no)
        index =image_name_ex.split('_')[1]
        print(index)


        # Read the image
        image_path = os.path.join(images_path, image_name)
        image = cv2.imread(image_path)
     
        # Resize the image
        resized_image = cv2.resize(image, (224, 224))

        # Convert the image to grayscale
        # gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

        # Normalize the image
        normalized_image = resized_image
        # distorted_image = random_distortion(resized_image)
        # blurred_image = random_gaussian_blurring(resized_image)
        # rotated_image = random_rotation(resized_image)
        # scaled_image = random_scaling(resized_image)
        # noisy_image = random_noise(resized_image)
        # adjusted_image = random_contrast(resized_image)
        # morphed_image = random_morphology(resized_image)


        # Save the image
        # processed_image_path = os.path.join(processed_images_path, image_name)
        # cv2.imwrite(processed_image_path, normalized_image)

        # Add the preprocessed image and label to the lists
        if (int(index) >= 5 and int(index) <= 12):
            preprocessed_images_train.append(np.array(normalized_image))
            # preprocessed_images_train.append(np.array(distorted_image))
            # preprocessed_images_train.append(np.array(blurred_image))
            # preprocessed_images_train.append(np.array(rotated_image))
            # preprocessed_images_train.append(np.array(scaled_image))
            # preprocessed_images_train.append(np.array(adjusted_image))
            # preprocessed_images_train.append(np.array(noisy_image))
            # preprocessed_images_train.append(np.array(morphed_image))
            labels_train.append(image_no)
            # for _ in range(7):
            #     labels_train.append(image_no)
       
         
        else:
            preprocessed_images_test.append(normalized_image)
            labels_test.append(image_no)
            # preprocessed_images_test.extend([distorted_image, blurred_image, rotated_image, scaled_image,adjusted_image,noisy_image,morphed_image])
            # for _ in range(7):
            #     labels_test.append(image_no)
    # break

        
       
        

12_9
12
9
94_12
94
12
70_6
70
6
35_6
35
6
95_1
95
1
128_3
128
3
88_10
88
10
23_11
23
11
14_10
14
10
100_4
100
4
19_1
19
1
121_11
121
11
75_11
75
11
59_5
59
5
51_4
51
4
137_12
137
12
75_8
75
8
133_10
133
10
93_9
93
9
51_10
51
10
125_6
125
6
38_11
38
11
90_7
90
7
9_11
9
11
57_10
57
10
62_1
62
1
50_2
50
2
78_11
78
11
14_3
14
3
99_6
99
6
70_8
70
8
1_7
1
7
2_9
2
9
42_12
42
12
102_11
102
11
82_2
82
2
106_3
106
3
136_12
136
12
95_2
95
2
59_2
59
2
46_4
46
4
19_10
19
10
111_5
111
5
21_1
21
1
130_8
130
8
26_3
26
3
115_4
115
4
127_6
127
6
134_1
134
1
138_6
138
6
79_9
79
9
73_8
73
8
132_4
132
4
78_7
78
7
127_9
127
9
134_2
134
2
40_5
40
5
41_5
41
5
39_8
39
8
31_2
31
2
10_1
10
1
79_4
79
4
135_9
135
9
96_2
96
2
96_11
96
11
106_1
106
1
48_6
48
6
97_1
97
1
137_1
137
1
17_1
17
1
24_4
24
4
124_11
124
11
101_3
101
3
93_1
93
1
42_7
42
7
92_5
92
5
57_7
57
7
27_2
27
2
46_10
46
10
128_8
128
8
29_7
29
7
49_10
49
10
120_1
120
1
129_1
129
1
82_3
82
3
56_7
56
7
84_1
84
1
126_7
126
7
88_4
88
4
16_2
16
2
46_8
46
8


In [6]:
preprocessed_images_train[0].shape

(224, 224, 3)

In [7]:
# Convert the list of preprocessed images to a NumPy array

preprocessed_images_train = np.array(preprocessed_images_train)
preprocessed_images_test = np.array(preprocessed_images_test)

for image in preprocessed_images_train:
    print(image.shape)
    break
print(preprocessed_images_train.shape)
print(preprocessed_images_test.shape)

(224, 224, 3)
(1120, 224, 224, 3)
(560, 224, 224, 3)


In [8]:
labels_train = np.array(labels_train)
labels_test = np.array(labels_test)
print(labels_train.shape)
print(labels_test.shape)

(1120,)
(560,)


In [9]:
# Convert labels to numerical labels
label_encoder = LabelEncoder()
numerical_labels_train = label_encoder.fit_transform(labels_train)
numerical_labels_test = label_encoder.fit_transform(labels_test)


# Convert numerical labels to one-hot encoded format
one_hot_labels_train = to_categorical(numerical_labels_train)
one_hot_labels_test = to_categorical(numerical_labels_test)

print(one_hot_labels_train)
print("-========")
print(one_hot_labels_test)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
-========
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
epochs = 10
batch_size = 16
margin = 1  # Margin for constrastive loss.
x_train = preprocessed_images_train
y_train = one_hot_labels_train
x_test = preprocessed_images_test
y_test = one_hot_labels_test

In [11]:
print(f"{x_train.shape=}")
print(f"{y_train.shape=}")
print(f"{x_test.shape=}")
print(f"{y_test.shape=}")

x_train.shape=(1120, 224, 224, 3)
y_train.shape=(1120, 140)
x_test.shape=(560, 224, 224, 3)
y_test.shape=(560, 140)


In [12]:
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
#https://blog.paperspace.com/attention-mechanisms-in-computer-vision-cbam/
from __future__ import print_function
import keras
from keras.layers import Dense, Conv2D, BatchNormalization, Activation
from keras.layers import AveragePooling2D, Input, Flatten
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras.callbacks import ReduceLROnPlateau
from keras.preprocessing.image import ImageDataGenerator
from keras.regularizers import l2
from keras import backend as K
from keras.models import Model
from keras.datasets import cifar10

import numpy as np
import os

In [14]:
from keras.layers import GlobalAveragePooling2D, GlobalMaxPooling2D, Reshape, Dense, multiply, Permute, Concatenate, Conv2D, Add, Activation, Lambda
from keras import backend as K
from keras.activations import sigmoid

def attach_attention_module(net, attention_module):
  if attention_module == 'se_block': # SE_block
    net = se_block(net)
  elif attention_module == 'cbam_block': # CBAM_block
    net = cbam_block(net)
  else:
    raise Exception("'{}' is not supported attention module!".format(attention_module))

  return net

def se_block(input_feature, ratio=8):
	"""Contains the implementation of Squeeze-and-Excitation(SE) block.
	As described in https://arxiv.org/abs/1709.01507.
	"""
	
	channel_axis = 1 if K.image_data_format() == "channels_first" else -1
	channel = input_feature.shape[channel_axis]

	se_feature = GlobalAveragePooling2D()(input_feature)
	se_feature = Reshape((1, 1, channel))(se_feature)
	assert se_feature.shape[1:] == (1,1,channel)
	se_feature = Dense(channel // ratio,
					   activation='relu',
					   kernel_initializer='he_normal',
					   use_bias=True,
					   bias_initializer='zeros')(se_feature)
	assert se_feature.shape[1:] == (1,1,channel//ratio)
	se_feature = Dense(channel,
					   activation='sigmoid',
					   kernel_initializer='he_normal',
					   use_bias=True,
					   bias_initializer='zeros')(se_feature)
	assert se_feature.shape[1:] == (1,1,channel)
	if K.image_data_format() == 'channels_first':
		se_feature = Permute((3, 1, 2))(se_feature)

	se_feature = multiply([input_feature, se_feature])
	return se_feature

def cbam_block(cbam_feature, ratio=8):
	"""Contains the implementation of Convolutional Block Attention Module(CBAM) block.
	As described in https://arxiv.org/abs/1807.06521.
	"""
	
	cbam_feature = channel_attention(cbam_feature, ratio)
	cbam_feature = spatial_attention(cbam_feature)
	return cbam_feature

def channel_attention(input_feature, ratio=8):
	
	channel_axis = 1 if K.image_data_format() == "channels_first" else -1
	channel = input_feature.shape[channel_axis]
	
	shared_layer_one = Dense(channel//ratio,
							 activation='relu',
							 kernel_initializer='he_normal',
							 use_bias=True,
							 bias_initializer='zeros')
	shared_layer_two = Dense(channel,
							 kernel_initializer='he_normal',
							 use_bias=True,
							 bias_initializer='zeros')
	
	avg_pool = GlobalAveragePooling2D()(input_feature)    
	avg_pool = Reshape((1,1,channel))(avg_pool)
	assert avg_pool.shape[1:] == (1,1,channel)
	avg_pool = shared_layer_one(avg_pool)
	assert avg_pool.shape[1:] == (1,1,channel//ratio)
	avg_pool = shared_layer_two(avg_pool)
	assert avg_pool.shape[1:] == (1,1,channel)
	
	max_pool = GlobalMaxPooling2D()(input_feature)
	max_pool = Reshape((1,1,channel))(max_pool)
	assert max_pool.shape[1:] == (1,1,channel)
	max_pool = shared_layer_one(max_pool)
	assert max_pool.shape[1:] == (1,1,channel//ratio)
	max_pool = shared_layer_two(max_pool)
	assert max_pool.shape[1:] == (1,1,channel)
	
	cbam_feature = Add()([avg_pool,max_pool])
	cbam_feature = Activation('sigmoid')(cbam_feature)
	
	if K.image_data_format() == "channels_first":
		cbam_feature = Permute((3, 1, 2))(cbam_feature)
	
	return multiply([input_feature, cbam_feature])

def spatial_attention(input_feature):
	kernel_size = 7
	
	if K.image_data_format() == "channels_first":
		channel = input_feature.shape[1]
		cbam_feature = Permute((2,3,1))(input_feature)
	else:
		channel = input_feature.shape[-1]
		cbam_feature = input_feature
	
	avg_pool = Lambda(lambda x: K.mean(x, axis=3, keepdims=True))(cbam_feature)
	assert avg_pool.shape[-1] == 1
	max_pool = Lambda(lambda x: K.max(x, axis=3, keepdims=True))(cbam_feature)
	assert max_pool.shape[-1] == 1
	concat = Concatenate(axis=3)([avg_pool, max_pool])
	assert concat.shape[-1] == 2
	cbam_feature = Conv2D(filters = 1,
					kernel_size=kernel_size,
					strides=1,
					padding='same',
					activation='sigmoid',
					kernel_initializer='he_normal',
					use_bias=False)(concat)	
	assert cbam_feature.shape[-1] == 1
	
	if K.image_data_format() == "channels_first":
		cbam_feature = Permute((3, 1, 2))(cbam_feature)
		
	return multiply([input_feature, cbam_feature])
		
	

In [21]:
"""
ResNet v1
This is a revised implementation from Cifar10 ResNet example in Keras:
(https://github.com/keras-team/keras/blob/master/examples/cifar10_resnet.py)
[a] Deep Residual Learning for Image Recognition
https://arxiv.org/pdf/1512.03385.pdf
"""

from __future__ import print_function
import keras
from keras.layers import Dense, Conv2D, BatchNormalization, Activation
from keras.layers import AveragePooling2D, Input, Flatten
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras.callbacks import ReduceLROnPlateau
from keras.preprocessing.image import ImageDataGenerator
from keras.regularizers import l2
from keras import backend as K
from keras.models import Model

from keras.layers import Dropout
def resnet_layer(inputs,
                 num_filters=16,
                 kernel_size=3,
                 strides=1,
                 activation='relu',
                 batch_normalization=True,
                 conv_first=True):
    """2D Convolution-Batch Normalization-Activation stack builder
    # Arguments
        inputs (tensor): input tensor from input image or previous layer
        num_filters (int): Conv2D number of filters
        kernel_size (int): Conv2D square kernel dimensions
        strides (int): Conv2D square stride dimensions
        activation (string): activation name
        batch_normalization (bool): whether to include batch normalization
        conv_first (bool): conv-bn-activation (True) or
            bn-activation-conv (False)
    # Returns
        x (tensor): tensor as input to the next layer
    """
    conv = Conv2D(num_filters,
                  kernel_size=kernel_size,
                  strides=strides,
                  padding='same',
                  kernel_initializer='he_normal',
                  kernel_regularizer=l2(1e-4))

    x = inputs
    if conv_first:
        x = conv(x)
        if batch_normalization:
            x = BatchNormalization()(x)
        if activation is not None:
            x = Activation(activation)(x)
    else:
        if batch_normalization:
            x = BatchNormalization()(x)
        if activation is not None:
            x = Activation(activation)(x)
        x = conv(x)
        x=Dropout(0.5)(x)
    return x


def resnet_v1(input_shape, depth, num_classes=140, attention_module=None):
    """ResNet Version 1 Model builder [a]
    Stacks of 2 x (3 x 3) Conv2D-BN-ReLU
    Last ReLU is after the shortcut connection.
    At the beginning of each stage, the feature map size is halved (downsampled)
    by a convolutional layer with strides=2, while the number of filters is
    doubled. Within each stage, the layers have the same number filters and the
    same number of filters.
    Features maps sizes:
    stage 0: 32x32, 16
    stage 1: 16x16, 32
    stage 2:  8x8,  64
    The Number of parameters is approx the same as Table 6 of [a]:
    ResNet20 0.27M
    ResNet32 0.46M
    ResNet44 0.66M
    ResNet56 0.85M
    ResNet110 1.7M
    # Arguments
        input_shape (tensor): shape of input image tensor
        depth (int): number of core convolutional layers
        num_classes (int): number of classes (CIFAR10 has 10)
    # Returns
        model (Model): Keras model instance
    """
    if (depth - 2) % 6 != 0:
        raise ValueError('depth should be 6n+2 (eg 20, 32, 44 in [a])')
    # Start model definition.
    num_filters = 16
    num_res_blocks = int((depth - 2) / 6)

    inputs = Input(shape=input_shape)
    x = resnet_layer(inputs=inputs)
    # Instantiate the stack of residual units
    for stack in range(3):
        for res_block in range(num_res_blocks):
            strides = 1
            if stack > 0 and res_block == 0:  # first layer but not first stack
                strides = 2  # downsample
            y = resnet_layer(inputs=x,
                             num_filters=num_filters,
                             strides=strides)
            y = resnet_layer(inputs=y,
                             num_filters=num_filters,
                             activation=None)
            if stack > 0 and res_block == 0:  # first layer but not first stack
                # linear projection residual shortcut connection to match
                # changed dims
                x = resnet_layer(inputs=x,
                                 num_filters=num_filters,
                                 kernel_size=1,
                                 strides=strides,
                                 activation=None,
                                 batch_normalization=False)
            # attention_module
            if attention_module is not None:
                y = attach_attention_module(y, attention_module)
            x = keras.layers.add([x, y])
            x = Activation('relu')(x)
            # x = Dropout(0.5)(x)
        num_filters *= 2

    # Add classifier on top.
    # v1 does not use BN after last shortcut connection-ReLU
    x = AveragePooling2D(pool_size=8)(x)
    # print(x[0])
    y = Flatten()(x)
 
    z=Dense(1024)(y)
    
    outputs = Dense(num_classes,
                    activation='softmax',
                    kernel_initializer='he_normal')(y)

    # Instantiate model.
    model = Model(inputs=inputs, outputs=[outputs])
    return model

In [22]:
from tensorflow.keras.models import Model
from keras.layers import Input
depth = 20 # For ResNet, specify the depth (e.g. ResNet50: depth=50)
model = resnet_v1(input_shape=(224,224,3), depth=depth, attention_module=None)
# print([f.shape for f in features])
# how to get feature vector from last layer of the model
# https://stackoverflow.com/questions/41711190/keras-how-to-get-the-output-of-each-layer


In [23]:
def lr_schedule(epoch):
    """Learning Rate Schedule

    Learning rate is scheduled to be reduced after 80, 120, 160, 180 epochs.
    Called automatically every epoch as part of callbacks during training.

    # Arguments
        epoch (int): The number of epochs

    # Returns
        lr (float32): learning rate
    """
    lr = 1e-3
    if epoch > 180:
        lr *= 0.5e-3
    elif epoch > 160:
        lr *= 1e-3
    elif epoch > 120:
        lr *= 1e-2
    elif epoch > 80:
        lr *= 1e-1
    print('Learning rate: ', lr)
    return lr

In [24]:
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(lr=lr_schedule(0)),
              metrics=['accuracy'])
model.summary()


Learning rate:  0.001
Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d_21 (Conv2D)             (None, 224, 224, 16  448         ['input_2[0][0]']                
                                )                                                                 
                                                                                                  
 batch_normalization_19 (BatchN  (None, 224, 224, 16  64         ['conv2d_21[0][0]']              
 ormalization)                  )                                     

In [25]:
model.fit(x_train, y_train,
              batch_size=64,
              epochs=50,
              validation_data=(x_test, y_test),
              shuffle=True)

18/18 [==============================] - 414s 23s/step - loss: 0.1493 - accuracy: 1.0000 - val_loss: 1.4586 - val_accuracy: 0.7554
Epoch 28/50
11/18 [=================>............] - ETA: 2:13 - loss: 0.1487 - accuracy: 1.0000

KeyboardInterrupt: 

In [ ]:
# Score trained model.
scores = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])

In [24]:
import os
import cv2
import numpy as np
import pickle

concate_folder = '/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/fvc2006db2a_minutiae_features'
# Load the dictionary from the pickle file
with open("/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/features_dict_fvc2006_db2a.pkl", "rb") as file:
    features_dict = pickle.load(file)

folder = '/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/ICVGIP_reproduce/FVC2006DB2A'

for image_name in os.listdir(folder):
    # compare feature_dict keys with image name
    if image_name.endswith('.bmp'):
        # Extract the label from the image name without considering variations
        image_name_ex = image_name.split('.')[0]

        # Check if the image name exists as a key in features_dict
        if image_name_ex in features_dict:
            # # Read the image
            # image_path = os.path.join(folder, image_name)
            # image = cv2.imread(image_path)
        
            # # Resize the image
            # resized_image = cv2.resize(image, (224, 224))

            # Get the corresponding features from features_dict
            features = features_dict[image_name_ex]

            # Predict using your model on the resized image
            # [feature_maps, y] = model.predict(np.array([resized_image]))

            # Concatenate the features with y
            # concatenated_features = np.concatenate([features, y], axis=1)
            concatenated_features = features
            print("Concatenated Features:,Name,ShAPE", concatenated_features,image_name_ex,concatenated_features.shape)
                        # Save concatenated features to a text file
            reshaped_features = np.reshape(concatenated_features, (32, 32, 1))
            output_file_path = os.path.join(concate_folder, f"{image_name_ex}.txt")
            np.save(output_file_path, reshaped_features)

Concatenated Features:,Name,ShAPE [[0.0000000e+00 1.1707586e+00 0.0000000e+00 5.5112511e-01 0.0000000e+00
  0.0000000e+00 2.0500624e-01 9.5713818e-01 0.0000000e+00 5.5511385e-02
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0498271e-01
  6.2247086e-01 7.7165306e-02 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.7592537e+00 2.9358178e-01 9.7937167e-01 0.0000000e+00 0.0000000e+00
  6.5657002e-01 0.0000000e+00 8.0535367e-02 0.0000000e+00 6.7648125e-01
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  8.1922078e-01 0.0000000e+00 1.5335967e-01 3.1231388e-01 1.4897772e+00
  5.4265946e-01 3.5649061e-01 4.8830327e-01 0.0000000e+00 8.7410116e-01
  1.1187955e+00 1.3359882e-01 6.4269722e-01 3.6479768e-01 3.6105010e-01
  1.5763147e+00 7.1723148e-02 0.0000000e+00 1.2558308e+00 0.0000000e+00
  5.1936114e-01 0.0000000e+00 0.0000000e+00 0.0000000e+00 5.0264609e-01
  9.5627576e-01 0.0000000e+00 0.0000000e+00 4.2423892e-01 0.0000000e+00
  6.1547834e-01 0.0000000e+00 

ValueError: cannot reshape array of size 512 into shape (32,32,1)

In [24]:
import os
import cv2
import numpy as np
import pickle

concate_folder = '/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/concat'
# Load the dictionary from the pickle file
with open("/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/features_dict.pkl", "rb") as file:
    features_dict = pickle.load(file)

folder = '/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/FVC2002DB2A'

for image_name in os.listdir(folder):
    # compare feature_dict keys with image name
    if image_name.endswith('.tif'):
        # Extract the label from the image name without considering variations
        image_name_ex = image_name.split('.')[0]

        # Check if the image name exists as a key in features_dict
        if image_name_ex in features_dict:
            # Read the image
            image_path = os.path.join(folder, image_name)
            image = cv2.imread(image_path)
        
            # Resize the image
            resized_image = cv2.resize(image, (224, 224))

            # Get the corresponding features from features_dict
            features = features_dict[image_name_ex]

            # Predict using your model on the resized image
            [feature_maps, y] = model.predict(np.array([resized_image]))

            # Concatenate the features with y
            concatenated_features = np.concatenate([features, y], axis=1)
            print("Concatenated Features:,Name,ShAPE", concatenated_features,image_name_ex,concatenated_features.shape)
                        # Save concatenated features to a text file
            reshaped_features = np.reshape(concatenated_features, (32, 32, 1))
            output_file_path = os.path.join(concate_folder, f"{image_name_ex}.txt")
            np.save(output_file_path, reshaped_features)

KeyboardInterrupt: 

In [60]:
loaded_concatenated_features = np.load('/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/concat/1_1.txt.npy')
loaded_concatenated_features

array([[[ 6.9223732e-01],
        [ 1.2410707e-01],
        [ 6.4937544e-01],
        ...,
        [ 0.0000000e+00],
        [ 0.0000000e+00],
        [ 6.3157910e-01]],

       [[ 6.7731172e-02],
        [ 9.8376459e-01],
        [ 0.0000000e+00],
        ...,
        [ 0.0000000e+00],
        [ 1.7061598e+00],
        [ 1.1149155e-01]],

       [[ 3.7743852e-01],
        [ 0.0000000e+00],
        [ 0.0000000e+00],
        ...,
        [ 0.0000000e+00],
        [ 0.0000000e+00],
        [ 1.2844551e+00]],

       ...,

       [[ 2.8595544e+02],
        [-3.4007400e+03],
        [ 2.8304141e+03],
        ...,
        [ 6.1458191e+02],
        [ 2.2444226e+02],
        [-4.8813081e+03]],

       [[ 1.4468853e+03],
        [-2.3620667e+03],
        [ 4.1082144e+03],
        ...,
        [-6.6500474e+03],
        [ 2.5831941e+03],
        [-2.5019561e+03]],

       [[-5.2927236e+03],
        [-2.2255435e+03],
        [ 4.3102114e+03],
        ...,
        [ 5.2767563e+03],
        [-6.192

In [23]:
print(concatenated_features)
reshaped_features = np.reshape(concatenated_features, (32, 32, 1))
print(reshaped_features)


[[ 0.0000000e+00  5.0060689e-01  0.0000000e+00 ...  4.5824536e+03
  -5.1262344e+03  2.8709363e+03]]
[[[ 0.0000000e+00]
  [ 5.0060689e-01]
  [ 0.0000000e+00]
  ...
  [ 1.6902678e+00]
  [ 8.8624203e-01]
  [ 1.6645782e-01]]

 [[ 0.0000000e+00]
  [ 0.0000000e+00]
  [ 1.7367622e-01]
  ...
  [ 0.0000000e+00]
  [ 0.0000000e+00]
  [ 0.0000000e+00]]

 [[ 0.0000000e+00]
  [ 8.3741939e-01]
  [ 6.5208837e-02]
  ...
  [ 0.0000000e+00]
  [ 6.9417167e-01]
  [ 1.2916510e+00]]

 ...

 [[ 8.0597052e+02]
  [-3.0533586e+03]
  [ 2.6234236e+03]
  ...
  [ 2.6094952e+02]
  [ 2.6577686e+02]
  [-4.1795122e+03]]

 [[ 1.1937926e+03]
  [-2.2541482e+03]
  [ 4.3962710e+03]
  ...
  [-5.4779619e+03]
  [ 2.3272324e+03]
  [-2.2961184e+03]]

 [[-4.3097466e+03]
  [-1.6759949e+03]
  [ 4.2352471e+03]
  ...
  [ 4.5824536e+03]
  [-5.1262344e+03]
  [ 2.8709363e+03]]]


In [25]:
from matplotlib import pyplot as plt
import numpy as np
import cv2
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import Sequential, Model
from keras.models import Model
from keras.layers import Input, Conv2D, MaxPool2D, Flatten, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda,Activation,Dense
from keras.optimizers import Adam
from tensorflow.keras.utils import plot_model
import tensorflow as tf

In [26]:
#Convolutional block 
def conv_block(input, num_filters):
    x = Conv2D(num_filters,3,padding="same")(input)
    x = BatchNormalization()(x)   #Not in the original network. 
    x = Activation("relu")(x)

    x = Conv2D(num_filters,3,padding="same")(x)
    x = BatchNormalization()(x)  #Not in the original network
    x = Activation("relu")(x)

    return x

#Encoder block: Conv block followed by maxpooling
def encoder_block(input, num_filters):
    x = conv_block(input, num_filters)
    p = MaxPool2D((2, 2))(x)
    return x, p 

In [29]:
def build_encoder(input_image):
    #inputs = Input(input_shape)

    s1, p1 = encoder_block(input_image, 32)
    s2, p2 = encoder_block(p1, 64)
    s3, p3 = encoder_block(p2, 128)
    s4, p4 = encoder_block(p3, 256)
    # b4 = BilinearUpSampling((374,388))(s4)
    s5,p5 = encoder_block(p4, 512)
    # b5 = BilinearUpSampling((374,388))(s5)
    # concat = concatenate([b4, b5])
    # print(concat.shape)
    f6 = Flatten()(p5)
    print(f6.shape)
    # f6 = Dense(10, activation='relu')(f6)
   
    return f6


def build_autoencoder(input_shape):
    input_img = Input(shape=input_shape)
    autoencoder = Model(input_img,build_encoder(input_img))
    return(autoencoder)

embedding_network=build_autoencoder((32,32,1))
embedding_network.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
print(embedding_network.summary())


(None, 512)
(None, 512)
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 32, 32, 1)]       0         
                                                                 
 conv2d_146 (Conv2D)         (None, 32, 32, 32)        320       
                                                                 
 batch_normalization_118 (Ba  (None, 32, 32, 32)       128       
 tchNormalization)                                               
                                                                 
 activation_142 (Activation)  (None, 32, 32, 32)       0         
                                                                 
 conv2d_147 (Conv2D)         (None, 32, 32, 32)        9248      
                                                                 
 batch_normalization_119 (Ba  (None, 32, 32, 32)       128       
 tchNormalization)                 

In [30]:
# Provided two tensors t1 and t2
# Euclidean distance = sqrt(sum(square(t1-t2)))
import numpy as np
def euclidean_distance(vects):
    """Find the Euclidean distance between two vectors.

    Arguments:
        vects: List containing two tensors of same length.

    Returns:
        Tensor containing euclidean  distance
        (as floating point value) between vectors.
    """

    x, y = vects
    sum_square = tf.math.reduce_sum(tf.math.square(x - y), axis=1, keepdims=True)
    return tf.math.sqrt(tf.math.maximum(sum_square, tf.keras.backend.epsilon()))


In [36]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Input
from tensorflow.keras import layers

In [38]:

input_1 = layers.Input(( 32, 32,1))
input_2 = layers.Input(( 32, 32,1))

# As mentioned above, Siamese Network share weights between
# tower networks (sister networks). To allow this, we will use
# same embedding network for both tower networks.
tower_1 = embedding_network(input_1)
tower_2 = embedding_network(input_2)

merge_layer = layers.Lambda(euclidean_distance)([tower_1, tower_2])
print(merge_layer.shape)
normal_layer = tf.keras.layers.BatchNormalization()(merge_layer)
output_layer = layers.Dense(1, activation="sigmoid")(normal_layer)
siamese = keras.Model(inputs=[input_1, input_2], outputs=output_layer)


(None, 1)


In [39]:

def loss(margin=1):
    """Provides 'constrastive_loss' an enclosing scope with variable 'margin'.

    Arguments:
        margin: Integer, defines the baseline for distance for which pairs
                should be classified as dissimilar. - (default is 1).

    Returns:
        'constrastive_loss' function with data ('margin') attached.
    """

    # Contrastive loss = mean( (1-true_value) * square(prediction) +
    #                         true_value * square( max(margin-prediction, 0) ))
    def contrastive_loss(y_true, y_pred):
        """Calculates the constrastive loss.

        Arguments:
            y_true: List of labels, each label is of type float32.
            y_pred: List of predictions of same length as of y_true,
                    each label is of type float32.

        Returns:
            A tensor containing constrastive loss as floating point value.
        """

        square_pred = tf.math.square(y_pred)
        margin_square = tf.math.square(tf.math.maximum(margin - (y_pred), 0))
        return tf.math.reduce_mean(
            (1 - y_true) * square_pred + (y_true) * margin_square
        )

    return contrastive_loss


In [40]:
siamese.compile(loss=loss(margin=margin), optimizer="RMSprop", metrics=["accuracy"])
siamese.summary()

Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_8 (InputLayer)           [(None, 32, 32, 1)]  0           []                               
                                                                                                  
 input_9 (InputLayer)           [(None, 32, 32, 1)]  0           []                               
                                                                                                  
 model_4 (Functional)           (None, 512)          4719584     ['input_8[0][0]',                
                                                                  'input_9[0][0]']                
                                                                                                  
 lambda_49 (Lambda)             (None, 1)            0           ['model_4[2][0]',          

In [135]:
test_loss, test_accuracy = model.evaluate(preprocessed_images_test, one_hot_labels_test)

10/10 [==============================] - 46s 5s/step - loss: 6.3407 - accuracy: 0.2800


In [ ]:
# visualize feature maps output from each block in the vgg model
# from keras.applications.vgg16 import VGG16

# from keras.models import Model
from matplotlib import pyplot
from numpy import expand_dims
# load the model
# model = VGG16()
# redefine model to output right after the first hidden layer
# ixs = [2, 5, 9, 15, 17]
# outputs = [model.layers[i].output for i in ixs]
# model = Model(inputs=model.inputs, outputs=outputs)
# load the image with the required shape
 # Read the image

image = cv2.imread('/home/rs/21CS91R01/research/2023_ICVGIP-Code-1/baseline1/DB1_A/1_1.tif')

        # Resize the image
resized_image = cv2.resize(image, (224, 224))

        # Convert the image to grayscale
        # gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

        # Normalize the image
normalized_image = resized_image
# expand dimensions so that it represents a single 'sample'
img = expand_dims(normalized_image, axis=0)
# prepare the image (e.g. scale pixel values for the vgg)
# img = preprocess_input(img)
# get feature map for first hidden layer
feature_maps = model.predict(img)
print(feature_maps[0].shape)
# plot the output from each block
# square = 8
# for fmap in feature_maps:
# 	# plot all 64 maps in an 8x8 squares
# 	ix = 1
# 	for _ in range(square):
# 		for _ in range(square):
# 			# specify subplot and turn of axis
# 			ax = pyplot.subplot(square, square, ix)
# 			ax.set_xticks([])
# 			ax.set_yticks([])
# 			# plot filter channel in grayscale
# 			pyplot.imshow(fmap[0, :, :, ix-1], cmap='gray')
# 			ix += 1
# 	# show the figure
# 	pyplot.show()