# Code to read images from FVC2006 DB2_A

In [9]:
import cv2
import os
# Get the path to the images
images_path = '/home/rs/21CS91R01/research/2023_ICVGIP-Code/datasets/DB2_A'

# List the images in the folder
images = os.listdir(images_path)

# Iterate over the images
for image in images:
  # Read the image
  image = cv2.imread(os.path.join(images_path, image))

  # Display the image
  # cv2_imshow(image)
  cv2.waitKey(0)

In [10]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import numpy as np

In [45]:
processed_images_path = '/home/rs/21CS91R01/research/2023_ICVGIP-Code/datasets/processed_images_path'
if not os.path.exists(processed_images_path):
    os.mkdir(processed_images_path)

# List to store preprocessed images
preprocessed_images_train = []
labels_train = []

preprocessed_images_test = []
labels_test = []

# Iterate over the images
for image_name in os.listdir(images_path):
    if image_name.endswith('.bmp'):
        # Extract the label from the image name without considering variations
        image_name_ex = image_name.split('.')[0]
        image_no = image_name_ex.split('_')[0]
        index =image_name_ex.split('_')[1]


        # Read the image
        image_path = os.path.join(images_path, image_name)
        image = cv2.imread(image_path)

        # Resize the image
        resized_image = cv2.resize(image, (224, 224))

        # Convert the image to grayscale
        gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

        # Normalize the image
        normalized_image = gray_image

        # Save the image
        processed_image_path = os.path.join(processed_images_path, image_name)
        cv2.imwrite(processed_image_path, normalized_image)

        # Add the preprocessed image and label to the lists
        if (int(index) >= 5 and int(index) <= 12):
          preprocessed_images_train.append(normalized_image)
          labels_train.append(image_no)
        else:
          preprocessed_images_test.append(normalized_image)
          labels_test.append(image_no)



In [46]:
# Convert the list of preprocessed images to a NumPy array
preprocessed_images_train = np.array(preprocessed_images_train)
preprocessed_images_test = np.array(preprocessed_images_test)
print(preprocessed_images_train.shape)

(1120, 224, 224)


In [47]:
labels_train = np.array(labels_train)
labels_test = np.array(labels_test)
print(labels_train.shape)

(1120,)


In [48]:
# Convert labels to numerical labels
label_encoder = LabelEncoder()
numerical_labels_train = label_encoder.fit_transform(labels_train)
numerical_labels_test = label_encoder.fit_transform(labels_test)


# Convert numerical labels to one-hot encoded format
one_hot_labels_train = to_categorical(numerical_labels_train)
one_hot_labels_test = to_categorical(numerical_labels_test)

print(one_hot_labels_train)
print("-========")
print(one_hot_labels_test)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
-========
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [49]:
epochs = 10
batch_size = 16
margin = 1  # Margin for constrastive loss.
x_train = preprocessed_images_train
y_train = one_hot_labels_train
x_test = preprocessed_images_test
y_test = one_hot_labels_test

In [66]:
x_train

array([[[2.5329625e-06, 2.6535797e-06, 2.8345055e-06, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [2.5932711e-06, 2.7741969e-06, 2.9551229e-06, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [2.7138883e-06, 2.8345055e-06, 3.0154315e-06, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        ...,
        [2.9551229e-06, 3.2566661e-06, 3.4375919e-06, ...,
         2.4726539e-06, 2.7741969e-06, 3.0154315e-06],
        [2.8948143e-06, 3.1360487e-06, 3.4375919e-06, ...,
         2.4726539e-06, 2.6535797e-06, 2.7741969e-06],
        [2.8345055e-06, 2.9551229e-06, 3.3169747e-06, ...,
         2.3520367e-06, 2.4726539e-06, 2.7741969e-06]],

       [[2.2314193e-06, 2.4123453e-06, 2.4123453e-06, ...,
         6.6339493e-07, 5.4277768e-07, 4.2216041e-07],
        [2.2917282e-06, 2.5329625e-06, 2.5329625e-06, ...,
         7.8401217e-07, 5.4277768e-07, 4.8246909e-07],
        [2.5329625e-06, 2.5329625e-06, 2.5329625e-06, ...,
         7.840

In [51]:
print(f"{x_train.shape=}")
print(f"{y_train.shape=}")
print(f"{x_test.shape=}")
print(f"{y_test.shape=}")

x_train.shape=(1120, 224, 224)
y_train.shape=(1120, 140)
x_test.shape=(560, 224, 224)
y_test.shape=(560, 140)


In [52]:
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Mobilenet

In [77]:
import matplotlib.pyplot as plt
import cv2
import numpy as np
import keras
import numpy as np # linear algebra
import keras.backend as K 
import time as ti 
import cv2
import os
import glob # for including images
import scipy.io as sio
from sklearn.metrics import classification_report, confusion_matrix
from keras import layers
from keras import models
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Dropout, Flatten, Activation, GlobalAveragePooling2D
from tensorflow.python.keras.layers import Conv2D, DepthwiseConv2D, MaxPooling2D, AveragePooling2D  
# from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
# from tensorflow.python.keras.optimizers import RMSprop, SGD, Adadelta, Adam 
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.applications import MobileNetV2

In [78]:
model = MobileNetV2(input_shape=(224, 224, 1), alpha=1, weights=None,classes=140)
model.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])
print(model.summary())

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_18 (InputLayer)          [(None, 224, 224, 1  0           []                               
                                )]                                                                
                                                                                                  
 Conv1 (Conv2D)                 (None, 112, 112, 32  288         ['input_18[0][0]']               
                                )                                                                 
                                                                                                  
 bn_Conv1 (BatchNormalization)  (None, 112, 112, 32  128         ['Conv1[0][0]']                  
                                )                                              

In [80]:
input_shape=(224,224,1)
epochs=50

result =model.fit(preprocessed_images_train, one_hot_labels_train, epochs=50, batch_size=32)

Epoch 1/50
35/35 [==============================] - 94s 2s/step - loss: 5.1423 - accuracy: 0.0098
Epoch 2/50
35/35 [==============================] - 81s 2s/step - loss: 4.2785 - accuracy: 0.0491
Epoch 3/50
35/35 [==============================] - 81s 2s/step - loss: 3.7234 - accuracy: 0.1009
Epoch 4/50
35/35 [==============================] - 80s 2s/step - loss: 2.9112 - accuracy: 0.2339
Epoch 5/50
35/35 [==============================] - 80s 2s/step - loss: 2.2615 - accuracy: 0.3580
Epoch 6/50
35/35 [==============================] - 80s 2s/step - loss: 1.7196 - accuracy: 0.5080
Epoch 7/50
35/35 [==============================] - 81s 2s/step - loss: 1.2219 - accuracy: 0.6429
Epoch 8/50
35/35 [==============================] - 78s 2s/step - loss: 0.8206 - accuracy: 0.7830
Epoch 9/50
35/35 [==============================] - 79s 2s/step - loss: 0.6759 - accuracy: 0.8134
Epoch 10/50
35/35 [==============================] - 79s 2s/step - loss: 0.4186 - accuracy: 0.9036
Epoch 11/50
35/35 [

In [82]:
test_loss, test_accuracy = model.evaluate(preprocessed_images_test, one_hot_labels_test)

18/18 [==============================] - 69s 4s/step - loss: 11.6394 - accuracy: 0.0071


In [83]:
import tensorflow as tf

class AttentionModule(tf.keras.layers.Layer):
    def __init__(self, in_channels):
        super(AttentionModule, self).__init__()
        self.query_conv = tf.keras.layers.Conv2D(in_channels // 8, kernel_size=1)
        self.key_conv = tf.keras.layers.Conv2D(in_channels // 8, kernel_size=1)
        self.value_conv = tf.keras.layers.Conv2D(in_channels, kernel_size=1)
        self.gamma = tf.Variable(tf.zeros((1,)), trainable=True)

    def call(self, inputs):
        batch_size, height, width, channels = tf.shape(inputs)

        # Query branch
        query = tf.transpose(self.query_conv(inputs), perm=[0, 3, 1, 2])
        query = tf.reshape(query, (batch_size, -1, height * width))

        # Key and Value branches
        key = tf.reshape(self.key_conv(inputs), (batch_size, -1, height * width))
        value = tf.reshape(self.value_conv(inputs), (batch_size, -1, height * width))

        # Attention calculation
        attention_weights = tf.matmul(query, key, transpose_b=True)
        attention_weights = tf.nn.softmax(attention_weights, axis=-1)

        # Weighted sum of values
        attention_output = tf.matmul(attention_weights, value)
        attention_output = tf.reshape(attention_output, (batch_size, height, width, channels))

        # Element-wise fusion
        attention_output = self.gamma * attention_output + inputs

        return attention_output

# Example usage
input_image = tf.random.normal((1, 224, 224, 3))  # Example input image tensor
attention_module = AttentionModule(in_channels=3)
output = attention_module(input_image)


ValueError: Invalid value for argument `filters`. Expected a strictly positive value. Received filters=0.

In [71]:
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow
from keras.layers import Input,Conv2D,MaxPooling2D,UpSampling2D
from keras.models import Model
from keras.optimizers import RMSprop


In [74]:
input_img = Input(shape = (224,224, 1))
def autoencoder(input_img):
    #encoder
    #input = 28 x 28 x 1 (wide and thin)
    conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(input_img) #28 x 28 x 32
    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1) #14 x 14 x 32
    conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(pool1) #14 x 14 x 64
    pool2 = MaxPooling2D(pool_size=(2, 2))(conv2) #7 x 7 x 64
    conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool2) #7 x 7 x 128 (small and thick)#decoder
    conv4 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv3) #7 x 7 x 128
    up1 = UpSampling2D((2,2))(conv4) # 14 x 14 x 128
    conv5 = Conv2D(64, (3, 3), activation='relu', padding='same')(up1) # 14 x 14 x 64
    up2 = UpSampling2D((2,2))(conv5) # 28 x 28 x 64
    decoded = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(up2) # 28 x 28 x 1
    return decoded
autoencoder = Model(input_img, autoencoder(input_img))

autoencoder.compile(loss='mean_squared_error', optimizer = RMSprop(), metrics=['accuracy'])
autoencoder.summary()

Model: "model_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_17 (InputLayer)       [(None, 224, 224, 1)]     0         
                                                                 
 conv2d_168 (Conv2D)         (None, 224, 224, 32)      320       
                                                                 
 max_pooling2d_17 (MaxPoolin  (None, 112, 112, 32)     0         
 g2D)                                                            
                                                                 
 conv2d_169 (Conv2D)         (None, 112, 112, 64)      18496     
                                                                 
 max_pooling2d_18 (MaxPoolin  (None, 56, 56, 64)       0         
 g2D)                                                            
                                                                 
 conv2d_170 (Conv2D)         (None, 56, 56, 128)       7385

In [75]:
#Training
batch_size = 128
epochs = 30
autoencoder_train = autoencoder.fit(x_train, x_train, batch_size=batch_size,epochs=epochs,verbose=1)


Epoch 1/30
9/9 [==============================] - 85s 9s/step - loss: 0.0737 - accuracy: 0.0112
Epoch 2/30
9/9 [==============================] - 80s 9s/step - loss: 2.2123e-05 - accuracy: 0.0112
Epoch 3/30
9/9 [==============================] - 86s 10s/step - loss: 5.5401e-06 - accuracy: 0.0112
Epoch 4/30
9/9 [==============================] - 90s 10s/step - loss: 2.7483e-06 - accuracy: 0.0112
Epoch 5/30
9/9 [==============================] - 81s 9s/step - loss: 1.5675e-06 - accuracy: 0.0112
Epoch 6/30
9/9 [==============================] - 75s 8s/step - loss: 9.3442e-07 - accuracy: 0.0112
Epoch 7/30
9/9 [==============================] - 75s 8s/step - loss: 5.6836e-07 - accuracy: 0.0112
Epoch 8/30
9/9 [==============================] - 77s 8s/step - loss: 3.5233e-07 - accuracy: 0.0112
Epoch 9/30
9/9 [==============================] - 76s 8s/step - loss: 2.2326e-07 - accuracy: 0.0112
Epoch 10/30
9/9 [==============================] - 78s 9s/step - loss: 1.4511e-07 - accuracy: 0.0112
E

In [76]:
test_loss, test_accuracy = autoencoder.evaluate(x_test, x_test)

18/18 [==============================] - 11s 570ms/step - loss: 2.2276e-10 - accuracy: 0.0108


In [58]:
from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda
from keras.optimizers import Adam
from keras.layers import Activation, MaxPool2D, Concatenate

#Convolutional block to be used in autoencoder and U-Net
def conv_block(input, num_filters):
    x = Conv2D(num_filters, 3, padding="same")(input)
    x = BatchNormalization()(x)   #Not in the original network. 
    x = Activation("relu")(x)

    x = Conv2D(num_filters, 3, padding="same")(x)
    x = BatchNormalization()(x)  #Not in the original network
    x = Activation("relu")(x)

    return x

#Encoder block: Conv block followed by maxpooling
def encoder_block(input, num_filters):
    x = conv_block(input, num_filters)
    p = MaxPool2D((2, 2))(x)
    return x, p   

#Decoder block for autoencoder (no skip connections)
def decoder_block(input, num_filters):
    x = Conv2DTranspose(num_filters, (2, 2), strides=2, padding="same")(input)
    x = conv_block(x, num_filters)
    return x

#Encoder will be the same for Autoencoder and U-net
#We are getting both conv output and maxpool output for convenience.
#we will ignore conv output for Autoencoder. It acts as skip connections for U-Net
def build_encoder(input_image):
    #inputs = Input(input_shape)

    s1, p1 = encoder_block(input_image, 32)
    s2, p2 = encoder_block(p1, 64)
    s3, p3 = encoder_block(p2, 128)
    
    encoded = conv_block(p3, 256) #Bridge
    
    return encoded

#Decoder for Autoencoder ONLY. 
def build_decoder(encoded):
    d1 = decoder_block(encoded, 128)
    d2 = decoder_block(d1, 64)
    d3 = decoder_block(d2, 32)
     
    decoded = Conv2D(3, 3, padding="same", activation="sigmoid")(d3)
    return decoded

#Use encoder and decoder blocks to build the autoencoder. 
def build_autoencoder(input_shape):
    input_img = Input(shape=input_shape)
    autoencoder = Model(input_img, build_decoder(build_encoder(input_img)))
    return(autoencoder)

In [67]:
input_shape = (224,224,1)
model=build_autoencoder(input_shape)
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])
print(model.summary())

Model: "model_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_14 (InputLayer)       [(None, 224, 224, 1)]     0         
                                                                 
 conv2d_141 (Conv2D)         (None, 224, 224, 32)      320       
                                                                 
 batch_normalization_203 (Ba  (None, 224, 224, 32)     128       
 tchNormalization)                                               
                                                                 
 activation_42 (Activation)  (None, 224, 224, 32)      0         
                                                                 
 conv2d_142 (Conv2D)         (None, 224, 224, 32)      9248      
                                                                 
 batch_normalization_204 (Ba  (None, 224, 224, 32)     128       
 tchNormalization)                                         

In [68]:
model.fit(x_train, x_train,
        epochs=10,
        shuffle=True)


Epoch 1/10


ValueError: in user code:

    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1024, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1082, in compute_loss
        return self.compiled_loss(
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/losses.py", line 284, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/losses.py", line 1500, in mean_squared_error
        return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)

    ValueError: Dimensions must be equal, but are 224 and 32 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](model_6/conv2d_155/Sigmoid, IteratorGetNext:1)' with input shapes: [32,224,224,3], [32,224,224].


In [36]:
import tensorflow as tf
#https://journalofcloudcomputing.springeropen.com/counter/pdf/10.1186/s13677-020-00203-9.pdf
#https://towardsdatascience.com/building-mobilenet-from-scratch-using-tensorflow-ad009c5dd42c
#import all necessary layers
from tensorflow.keras.layers import Input, DepthwiseConv2D
from tensorflow.keras.layers import Conv2D, BatchNormalization,GlobalAveragePooling2D
from tensorflow.keras.layers import ReLU, AvgPool2D, Flatten, Dense
from tensorflow.keras import Model
# MobileNet block
def mobilnet_block (x, filters, strides):
    
    x = DepthwiseConv2D(kernel_size = 3, strides = strides,dilation_rate=3, padding = 'same')(x)
    x = DepthwiseConv2D(kernel_size = 3, strides = strides, padding = 'same')(x)
    x = BatchNormalization()(x)
    x = ReLU()(x)
    
    x = Conv2D(filters = filters, kernel_size = 1, strides = 1)(x)
    x = BatchNormalization()(x)
    x = ReLU()(x)
    
    return x
#stem of the model
input = Input(shape = (224,224,1))
x = Conv2D(filters = 32, kernel_size = 3, strides = 1, padding = 'same')(input)
x = BatchNormalization()(x)
x = ReLU()(x)
# main part of the model
x = mobilnet_block(x, filters = 64, strides = 1)
x = mobilnet_block(x, filters = 128, strides = 1)
x = mobilnet_block(x, filters = 128, strides = 1)
x = mobilnet_block(x, filters = 256, strides = 1)
x = mobilnet_block(x, filters = 256, strides = 1)
x = mobilnet_block(x, filters = 512, strides = 1)
for _ in range (5):
     x = mobilnet_block(x, filters = 512, strides = 1)
x = mobilnet_block(x, filters = 1024, strides = 1)
x = mobilnet_block(x, filters = 1024, strides = 1)
x = AvgPool2D (pool_size = 7, strides = 1, data_format='channels_first')(x)
output = Dense (units = 140, activation = 'softmax')(x)
model = Model(inputs=input, outputs=output)
model.summary()
#plot the model
# tf.keras.utils.plot_model(model, to_file='model.png', show_shapes=True, show_dtype=False,show_layer_names=True, rankdir='TB', expand_nested=False, dpi=96)

In [37]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

AttributeError: 'KerasTensor' object has no attribute 'compile'

In [30]:
# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=128)



Epoch 1/10


ValueError: in user code:

    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1024, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/training.py", line 1082, in compute_loss
        return self.compiled_loss(
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/losses.py", line 152, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/losses.py", line 284, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/losses.py", line 2004, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/home/rs/21CS91R01/anaconda3/envs/few_shot/lib/python3.10/site-packages/keras/backend.py", line 5532, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 140) and (None, 224, 218, 140) are incompatible
